#!/usr/bin/env node
import { Command } from "commander";
import { uploadCmd } from "./commands/upload.js";
import { statusCmd } from "./commands/status.js";
import { infoCmd } from "./commands/info.js";
import { aimodelCmd } from "./commands/aimodel.js";
import { aiproductCmd } from "./commands/aiproduct.js";
import { aiposeCmd } from "./commands/aipose.js";
import { expandimageCmd } from "./commands/expandimage.js";
import { removebgCmd } from "./commands/removebg.js";
import { virtualtryonCmd } from "./commands/virtualtryon.js";
import { qwenImageEditCmd } from "./commands/qwen-image-edit.js";
import { seedreamCmd } from "./commands/seedream.js";
import { faceForgeCmd } from "./commands/face-forge.js";
import { klingCmd } from "./commands/kling.js";
import { zImageCmd } from "./commands/z-image.js";
import { pregnantAiCmd } from "./commands/pregnant-ai.js";
import { futuristicEleganceCmd } from "./commands/futuristic-elegance.js";
import { aiDogCmd } from "./commands/ai-dog.js";
import { aiAgingCmd } from "./commands/ai-aging.js";
import { outfitGeneratorCmd } from "./commands/outfit-generator.js";
import { fatAiCmd } from "./commands/fat-ai.js";
import { genderSwapCmd } from "./commands/gender-swap.js";
import { chibiMakerCmd } from "./commands/chibi-maker.js";
import { flatLayCmd } from "./commands/flat-lay.js";
import { aiTranslateCmd } from "./commands/ai-translate.js";
import { aiPosterFromImagesCmd } from "./commands/ai-poster-from-images.js";
import { buzzCutAiCmd } from "./commands/buzz-cut-ai.js";
import { aiFaceMergeCmd } from "./commands/ai-face-merge.js";
import { skinColorChangerCmd } from "./commands/skin-color-changer.js";
import { baldFilterCmd } from "./commands/bald-filter.js";
import { aiChristmasPhotoCmd } from "./commands/ai-christmas-photo.js";
import { aiHairColorChangerCmd } from "./commands/ai-hair-color-changer.js";
import { aiImageCombinerCmd } from "./commands/ai-image-combiner.js";
import { aiXrayClothesCmd } from "./commands/ai-xray-clothes.js";
import { celebAiCmd } from "./commands/celeb-ai.js";
import { ps2FilterCmd } from "./commands/ps2-filter.js";
import { bracesFilterCmd } from "./commands/braces-filter.js";
import { sonicOcCmd } from "./commands/sonic-oc.js";
import { bangsFilterCmd } from "./commands/bangs-filter.js";
import { aiPosterCmd } from "./commands/ai-poster.js";
import { imageToSketchCmd } from "./commands/image-to-sketch.js";
import { mugshotCreatorCmd } from "./commands/mugshot-creator.js";
import { ai3dRenderingCmd } from "./commands/ai-3d-rendering.js";
import { aiElfCmd } from "./commands/ai-elf.js";
import { stardewValleyPortraitMakerCmd } from "./commands/stardew-valley-portrait-maker.js";
import { aiSelfieCmd } from "./commands/ai-selfie.js";
import { aiZombieCmd } from "./commands/ai-zombie.js";
import { aiFlagGeneratorCmd } from "./commands/ai-flag-generator.js";
import { wildGraffitiCmd } from "./commands/wild-graffiti.js";
import { aiBikiniModelCmd } from "./commands/ai-bikini-model.js";
import { aiSprayPaintCmd } from "./commands/ai-spray-paint.js";
import { squareFaceIconGeneratorCmd } from "./commands/square-face-icon-generator.js";
import { animeImageConverterCmd } from "./commands/anime-image-converter.js";
import { aiFeetCmd } from "./commands/ai-feet.js";
import { aiClothesChangerCmd } from "./commands/ai-clothes-changer.js";
import { photoToBikiniAiCmd } from "./commands/photo-to-bikini-ai.js";
import { bikiniTryOnCmd } from "./commands/bikini-try-on.js";
import { aiBikiniVideoCmd } from "./commands/ai-bikini-video.js";
import { aiSwimSuitModelCmd } from "./commands/ai-swimsuit-model.js";
import { aiBikiniPhotoEditorCmd } from "./commands/ai-bikini-photo-editor.js";
import { sexyAiPicsCmd } from "./commands/sexy-ai-pics.js";
import { aiBabeCmd } from "./commands/ai-babe.js";
import { dressRemoverMagicEraserCmd } from "./commands/dress-remover-magic-eraser.js";
import { clothingMagicRemoverCmd } from "./commands/clothing-magic-remover.js";
import { freeAiGirlfriendGeneratorCmd } from "./commands/free-ai-girlfriend-generator.js";
import { bratGeneratorCmd } from "./commands/brat-generator.js";
import { sprunkiOcMakerCmd } from "./commands/sprunki-oc-maker.js";
import { twoDTo3dImageConverterCmd } from "./commands/2d-to-3d-image-converter.js";
import { murderDronesOcCmd } from "./commands/murder-drones-oc.js";
import { randomAnimalGeneratorCmd } from "./commands/random-animal-generator.js";
import { aiCollageMakerCmd } from "./commands/ai-collage-maker.js";
import { aiGhostMannequinGeneratorCmd } from "./commands/ai-ghost-mannequin-generator.js";
import { aiPhotoshootCmd } from "./commands/ai-photoshoot.js";
import { aiTattooGeneratorCmd } from "./commands/ai-tattoo-generator.js";
import { aiHairstyleChangerCmd } from "./commands/ai-hairstyle-changer.js";
import { aiActionFigureGeneratorsCmd } from "./commands/ai-action-figure-generators.js";
import { ghibliArtCreateCmd } from "./commands/ghibli-art-create.js";
import { aiRoomPlannerCmd } from "./commands/ai-room-planner.js";
import { removeFilterFromPhotoCmd } from "./commands/remove-filter-from-photo.js";
import { demonSlayerOcMakerCmd } from "./commands/demon-slayer-oc-maker.js";
import { babyFaceGeneratorCmd } from "./commands/baby-face-generator.js";
import { aiLandscapeDesignFreeCmd } from "./commands/ai-landscape-design-free.js";
import { aiImageAnimationCmd } from "./commands/ai-image-animation.js";
import { aiWerewolfCmd } from "./commands/ai-werewolf.js";
import { midjourneyCmd } from "./commands/midjourney.js";
import { sora2Cmd } from "./commands/sora-2.js";
import { wanAiCmd } from "./commands/wan-ai.js";
import { seedanceCmd } from "./commands/seedance.js";
import { fireredImageEditCmd } from "./commands/firered-image-edit.js";
import { grokImagineCmd } from "./commands/grok-imagine.js";
import { grokImagineVideoCmd } from "./commands/grok-imagine-video.js";
import { videoWatermarkRemoverCmd } from "./commands/video-watermark-remover.js";
import { aiVideoEnhancerCmd } from "./commands/ai-video-enhancer.js";
import { replaceFaceInVideoOnlineFreeCmd } from "./commands/replace-face-in-video-online-free.js";
import { aiGeneratedBikiniGirlsCmd } from "./commands/ai-generated-bikini-girls.js";
import { sexAiGeneratorCmd } from "./commands/sex-ai-generator.js";
import { aiHotGirlImageCmd } from "./commands/ai-hot-girl-image.js";
import { aiGeneratedPerfectFemaleBodyCmd } from "./commands/ai-generated-perfect-female-body.js";
import { aiSexyTeensCmd } from "./commands/ai-sexy-teens.js";
import { cuteAnimeGirlAiBikiniCmd } from "./commands/cute-anime-girl-ai-bikini.js";
import { aiLingerieModelsCmd } from "./commands/ai-lingerie-models.js";
import { aiSexyPortraitCmd } from "./commands/ai-sexy-portrait.js";
import { freeSexyAiGeneratorCmd } from "./commands/free-sexy-ai-generator.js";
import { hotBikiniModelsCmd } from "./commands/hot-bikini-models.js";
import { happyWomanBikiniAiPicCmd } from "./commands/happy-woman-bikini-ai-pic.js";
import { bikiniContestPhotosCmd } from "./commands/bikini-contest-photos.js";
import { personalizedSwimSuitCmd } from "./commands/personalized-swimsuit.js";
import { customBikiniCmd } from "./commands/custom-bikini.js";
import { swimsuitTryOnHaulCmd } from "./commands/swimsuit-try-on-haul.js";
import { stringBikiniBeautyContestCmd } from "./commands/string-bikini-beauty-contest.js";
import { aiGroupPhotoGeneratorCmd } from "./commands/ai-group-photo-generator.js";
import { removeSubtitlesFromVideoOnlineFreeCmd } from "./commands/remove-subtitles-from-video-online-free.js";
import { aiTextRemoverFromVideoCmd } from "./commands/ai-text-remover-from-video.js";
import { logoRemoverFromVideoCmd } from "./commands/logo-remover-from-video.js";
import { geminiWatermarkRemoverCmd } from "./commands/gemini-watermark-remover.js";
import { removeTextFromVideoOnlineFreeCmd } from "./commands/remove-text-from-video-online-free.js";
import { videoUpscalerOnlineFreeCmd } from "./commands/video-upscaler-online-free.js";
import { videoResolutionEnhancerOnlineFreeCmd } from "./commands/video-resolution-enhancer-online-free.js";
import { improveVideoQualityOnlineFreeCmd } from "./commands/improve-video-quality-online-free.js";
import { freeOnlineVideoQualityEnhancerCmd } from "./commands/free-online-video-quality-enhancer.js";
import { free4kVideoUpscalerCmd } from "./commands/free-4k-video-upscaler.js";
import { seeThroughClothesFitlerCmd } from "./commands/see-through-clothes-fitler.js";
import { hairColorTryOnCmd } from "./commands/hair-color-try-on.js";
import { imageMixerCmd } from "./commands/image-mixer.js";

const program = new Command()
  .name("weshop")
  .version("0.2.0")
  .addHelpCommand(false)
  .description(
    "WeShop AI — generate, edit, and transform images and videos from the command line.\n\n" +
    "Set your API key:  export WESHOP_API_KEY=<key>\n" +
    "Get one at:        https://open.weshop.ai/authorization/apikey\n\n" +
    "Run 'weshop <command> --help' to see each agent's specific parameters and usage.\n\n" +
    "Examples:\n" +
    "  weshop upload ./photo.png\n" +
    "  weshop aimodel --image ./model.png --mask-type autoApparelSegment --generation-mode freeCreation --prompt 'street style'\n" +
    "  weshop kling --image ./scene.png --prompt 'Camera slowly pans across a misty forest'\n" +
    "  weshop removebg --image ./product.png --mask-type autoSubjectSegment --bg-hex '#ffffff'\n" +
    "  weshop status <executionId>"
  );

program.addCommand(uploadCmd);
program.addCommand(statusCmd);
program.addCommand(infoCmd);
program.addCommand(virtualtryonCmd);
program.addCommand(aimodelCmd);
program.addCommand(aiproductCmd);
program.addCommand(aiposeCmd);
program.addCommand(expandimageCmd);
program.addCommand(removebgCmd);
program.addCommand(qwenImageEditCmd);
program.addCommand(seedreamCmd);
program.addCommand(faceForgeCmd);
program.addCommand(klingCmd);
program.addCommand(zImageCmd);
program.addCommand(pregnantAiCmd);
program.addCommand(futuristicEleganceCmd);
program.addCommand(aiDogCmd);
program.addCommand(aiAgingCmd);
program.addCommand(outfitGeneratorCmd);
program.addCommand(fatAiCmd);
program.addCommand(genderSwapCmd);
program.addCommand(chibiMakerCmd);
program.addCommand(flatLayCmd);
program.addCommand(aiTranslateCmd);
program.addCommand(aiPosterFromImagesCmd);
program.addCommand(buzzCutAiCmd);
program.addCommand(aiFaceMergeCmd);
program.addCommand(skinColorChangerCmd);
program.addCommand(baldFilterCmd);
program.addCommand(aiChristmasPhotoCmd);
program.addCommand(aiHairColorChangerCmd);
program.addCommand(aiImageCombinerCmd);
program.addCommand(aiXrayClothesCmd);
program.addCommand(celebAiCmd);
program.addCommand(ps2FilterCmd);
program.addCommand(bracesFilterCmd);
program.addCommand(sonicOcCmd);
program.addCommand(bangsFilterCmd);
program.addCommand(aiPosterCmd);
program.addCommand(imageToSketchCmd);
program.addCommand(mugshotCreatorCmd);
program.addCommand(ai3dRenderingCmd);
program.addCommand(aiElfCmd);
program.addCommand(stardewValleyPortraitMakerCmd);
program.addCommand(aiSelfieCmd);
program.addCommand(aiZombieCmd);
program.addCommand(aiFlagGeneratorCmd);
program.addCommand(wildGraffitiCmd);
program.addCommand(aiBikiniModelCmd);
program.addCommand(aiSprayPaintCmd);
program.addCommand(squareFaceIconGeneratorCmd);
program.addCommand(animeImageConverterCmd);
program.addCommand(aiFeetCmd);
program.addCommand(aiClothesChangerCmd);
program.addCommand(photoToBikiniAiCmd);
program.addCommand(bikiniTryOnCmd);
program.addCommand(aiBikiniVideoCmd);
program.addCommand(aiSwimSuitModelCmd);
program.addCommand(aiBikiniPhotoEditorCmd);
program.addCommand(sexyAiPicsCmd);
program.addCommand(aiBabeCmd);
program.addCommand(dressRemoverMagicEraserCmd);
program.addCommand(clothingMagicRemoverCmd);
program.addCommand(freeAiGirlfriendGeneratorCmd);
program.addCommand(bratGeneratorCmd);
program.addCommand(sprunkiOcMakerCmd);
program.addCommand(twoDTo3dImageConverterCmd);
program.addCommand(murderDronesOcCmd);
program.addCommand(randomAnimalGeneratorCmd);
program.addCommand(aiCollageMakerCmd);
program.addCommand(aiGhostMannequinGeneratorCmd);
program.addCommand(aiPhotoshootCmd);
program.addCommand(aiTattooGeneratorCmd);
program.addCommand(aiHairstyleChangerCmd);
program.addCommand(aiActionFigureGeneratorsCmd);
program.addCommand(ghibliArtCreateCmd);
program.addCommand(aiRoomPlannerCmd);
program.addCommand(removeFilterFromPhotoCmd);
program.addCommand(demonSlayerOcMakerCmd);
program.addCommand(babyFaceGeneratorCmd);
program.addCommand(aiLandscapeDesignFreeCmd);
program.addCommand(aiImageAnimationCmd);
program.addCommand(aiWerewolfCmd);
program.addCommand(midjourneyCmd);
program.addCommand(sora2Cmd);
program.addCommand(wanAiCmd);
program.addCommand(seedanceCmd);
program.addCommand(fireredImageEditCmd);
program.addCommand(grokImagineCmd);
program.addCommand(grokImagineVideoCmd);
program.addCommand(videoWatermarkRemoverCmd);
program.addCommand(aiVideoEnhancerCmd);
program.addCommand(replaceFaceInVideoOnlineFreeCmd);
program.addCommand(aiGeneratedBikiniGirlsCmd);
program.addCommand(sexAiGeneratorCmd);
program.addCommand(aiHotGirlImageCmd);
program.addCommand(aiGeneratedPerfectFemaleBodyCmd);
program.addCommand(aiSexyTeensCmd);
program.addCommand(cuteAnimeGirlAiBikiniCmd);
program.addCommand(aiLingerieModelsCmd);
program.addCommand(aiSexyPortraitCmd);
program.addCommand(freeSexyAiGeneratorCmd);
program.addCommand(hotBikiniModelsCmd);
program.addCommand(happyWomanBikiniAiPicCmd);
program.addCommand(bikiniContestPhotosCmd);
program.addCommand(personalizedSwimSuitCmd);
program.addCommand(customBikiniCmd);
program.addCommand(swimsuitTryOnHaulCmd);
program.addCommand(stringBikiniBeautyContestCmd);
program.addCommand(aiGroupPhotoGeneratorCmd);
program.addCommand(removeSubtitlesFromVideoOnlineFreeCmd);
program.addCommand(aiTextRemoverFromVideoCmd);
program.addCommand(logoRemoverFromVideoCmd);
program.addCommand(geminiWatermarkRemoverCmd);
program.addCommand(removeTextFromVideoOnlineFreeCmd);
program.addCommand(videoUpscalerOnlineFreeCmd);
program.addCommand(videoResolutionEnhancerOnlineFreeCmd);
program.addCommand(improveVideoQualityOnlineFreeCmd);
program.addCommand(freeOnlineVideoQualityEnhancerCmd);
program.addCommand(free4kVideoUpscalerCmd);
program.addCommand(seeThroughClothesFitlerCmd);
program.addCommand(hairColorTryOnCmd);
program.addCommand(imageMixerCmd);

program.parse();
